# 50 common occupations
common_occupations = [
  "accountant",
  "actor",
  "architect",
  "artist",
  "attorney",
  "author",
  "baker",
  "banker",
  "barber",
  "bartender",
  "biologist",
  "butcher",
  "carpenter",
  "cashier",
  "chef",
  "chemist",
  "coach",
  "construction worker",
  "consultant",
  "dentist",
  "designer",
  "doctor",
  "driver",
  "electrician",
  "engineer",
  "farmer",
  "firefighter",
  "flight attendant",
  "graphic designer",
  "hairdresser",
  "journalist",
  "judge",
  "librarian",
  "mechanic",
  "nurse",
  "pharmacist",
  "photographer",
  "pilot",
  "plumber",
  "police officer",
  "professor",
  "programmer",
  "receptionist",
  "salesperson",
  "scientist",
  "secretary",
  "teacher",
  "technician",
  "translator",
  "veterinarian",
  "waiter"
]
